name:  CI pipeline

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    name: build && push image to docker hub
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build and push api
        id: build-push-api
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./graphql/app.dockerfile
          push: true
          tags: logilog/graphql:latest

      - name: build and push account-db
        id: build-push-account-db
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./account/db.dockerfile
          push: true
          tags: logilog/account-db:latest

      - name: build and push account-service
        id: build-push-account-service
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./account/app.dockerfile
          push: true
          tags: logilog/account-service:latest

      - name: build and push shopify-db
        id: build-push-shopify-db
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./shopify/db.dockerfile
          push: true
          tags: logilog/shopify-db:latest

      - name: build and push shopify-service
        id: build-push-shopify-service
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./shopify/app.dockerfile
          push: true
          tags: logilog/shopify-service:latest
